"""Constants for column names used in the procurement dashboard application."""

# data column
SOURCE = "Source"
DEPARTMENT = "Department"
AMOUNT = "Amount"
SUPPLIER = "Supplier"
PAYMENT_DATE = "Payment date"
PAYMENT_YEAR = "Payment year"
LATITUDE = "Latitude"
LONGITUDE = "Longitude"
GEOMETRY = "Geometry"
NUTS_ID_0 = "NUTS ID 0"
NUTS_NAME_0 = "NUTS Name 0"
NUTS_ID_1 = "NUTS ID 1"
NUTS_NAME_1 = "NUTS Name 1"
NUTS_ID_2 = "NUTS ID 2"
NUTS_NAME_2 = "NUTS Name 2"
NUTS_ID_3 = "NUTS ID 3"
NUTS_NAME_3 = "NUTS Name 3"
SPINE = "Is spine?"
MANUAL_MATCH = "Manual match to spine?"
OTHER_MATCH = "Other match to spine?"
REMOVED = "Removed?"
REMOVAL_DATE = "Removal date"

# calculated columns
TOTAL_VALUE_PAYMENTS = "Total amount"
TOTAL_PAYMENTS = "Total transactions"
